language: python
os:
- linux
python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'

script:
- python -m pytest hirata/ tests/ --cov=hirata
- make ccsd eom-ccsd ccsdt eom-ccsdt mbpt1 mbpt2

install:
- pip install .
- pip install setuptools
- pip install pytest
- pip install pytest-cov
