language: python
os:
- linux
python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'

script:
- python -m pytest hirata/ tests/ --cov=hirata

install:
- pip install .
- pip install setuptools
- pip install pytest
- pip install pytest-cov
