( - 0.5 )  *  Viajk["jclm"] * Labij["mlca"]
( - 0.5 )  *  Vabic["cdma"] * Labij["mjdc"]
( - 0.5 )  *  Tabij["cdmn"] * Vijka["njoa"] * Labij["omdc"]
( - 1.0 )  *  Tabij["cdmn"] * Vijka["njod"] * Labij["omca"]
( - 0.25 ) *  Tabij["cdmn"] * Vijka["mnoa"] * Labij["ojdc"]
( - 0.5 )  *  Tabij["cdmn"] * Vijka["mnod"] * Labij["ojca"]
( - 0.5 )  *  Tabij["cdmn"] * Viabc["jgda"] * Labij["nmgc"]
( - 0.25 ) *  Tabij["cdmn"] * Viabc["jgcd"] * Labij["nmga"]
( - 1.0 )  *  Tabij["cdmn"] * Viabc["ngda"] * Labij["mjgc"]
( - 0.5 )  *  Tabij["cdmn"] * Viabc["ngcd"] * Labij["mjga"]
