( - 1.0 + 1.0 * P("klab", "lkab") )     *  Fij["km"]              * Labij["mlab"]
( - 1.0 + 1.0 * P("klba", "klab") )     *  Fab["eb"]              * Labij["klea"]
( - 0.5 )     *  Vijkl["klmn"]          * Labij["nmab"]
( + 1.0 - 1.0 * P("klba", "klab") - 1.0 * P("klba", "lkba") + 1.0 * P("klba", "lkab") ) *  Viajb["kenb"] * Labij["nlea"]
( - 0.5 )     *  Vabcd["efab"]          * Labij["klfe"]
( + 0.5 - 0.5 * P("klba", "klab") )     *  Tabij["efop"]          * Vijab["klfb"]       * Labij["poea"]
( - 0.25 )    *  Tabij["efop"]          * Vijab["klef"]           * Labij["poab"]
( - 0.5 + 0.5 * P("klab", "lkab") )     *  Tabij["efop"]          * Vijab["pkab"]       * Labij["olfe"]
( - 1.0 + 1.0 * P("klba", "klab") + 1.0 * P("klba", "lkba") - 1.0 * P("klba", "lkab") ) *  Tabij["efop"] * Vijab["pkfb"] * Labij["olea"]
( + 0.5 - 0.5 * P("klab", "lkab") )     *  Tabij["efop"]          * Vijab["pkef"]       * Labij["olab"]
( - 0.25 )    *  Tabij["efop"]          * Vijab["opab"]           * Labij["klfe"]
( - 0.5 + 0.5 * P("klba", "klab") )     *  Tabij["efop"]          * Vijab["opfb"]       * Labij["klea"]
