( - 1.0 + 1.0 * P("cdij", "cdji") )     *  Fij["mi"]              * Rabij["cdmj"]
( - 1.0 + 1.0 * P("dcij", "cdij") )     *  Fab["de"]              * Rabij["ecij"]
( + 0.5 )     *  Vijkl["mnij"]          * Rabij["cdmn"]
( + 1.0 - 1.0 * P("dcij", "cdij") - 1.0 * P("dcij", "dcji") + 1.0 * P("dcij", "cdji") ) *  Viajb["mdif"] * Rabij["fcmj"]
( + 0.5 )     *  Vabcd["cdef"]          * Rabij["efij"]
( + 0.5 - 0.5 * P("dcij", "cdij") )     *  Tabij["edij"]          * Vijab["noeh"]       * Rabij["hcno"]
( + 0.25 )    *  Tabij["efij"]          * Vijab["opef"]           * Rabij["cdop"]
( - 0.5 + 0.5 * P("cdij", "cdji") )     *  Tabij["cdmi"]          * Vijab["mngh"]       * Rabij["ghnj"]
( - 1.0 + 1.0 * P("dcij", "cdij") + 1.0 * P("dcij", "dcji") - 1.0 * P("dcij", "cdji") ) *  Tabij["edni"] * Vijab["noeh"] * Rabij["hcoj"]
( - 0.5 + 0.5 * P("cdij", "cdji") )     *  Tabij["efoi"]          * Vijab["opef"]       * Rabij["cdpj"]
( + 0.25 )    *  Tabij["cdmn"]          * Vijab["mngh"]           * Rabij["ghij"]
( + 0.5 - 0.5 * P("dcij", "cdij") )     *  Tabij["edno"]          * Vijab["noeh"]       * Rabij["hcij"]
