( - 1.0 )  *  Fij["jk"]     * Lai["ka"]
( + 1.0 )  *  Fab["ca"]     * Lai["jc"]
( - 1.0 )  *  Vabij["jcla"] * Lai["lc"]
( - 0.5 )  *  Vabij["jclm"] * Labij["mlca"]
( - 0.5 )  *  Vabij["cdma"] * Labij["mjdc"]
( - 1.0 )  *  Tai["cl"]     * Vabij["ljma"] * Lai["mc"]
( + 1.0 )  *  Tai["cl"]     * Vabij["ljmc"] * Lai["ma"]
( - 1.0 )  *  Tai["cl"]     * Vabij["jeca"] * Lai["le"]
( + 1.0 )  *  Tai["cl"]     * Vabij["leca"] * Lai["je"]
( - 1.0 )  *  Fij["kl"]     * Tai["ek"]     * Labij["ljea"]
( + 1.0 )  *  Fab["cd"]     * Tai["dm"]     * Labij["mjca"]
( - 0.5 )  *  Tai["cl"]     * Vabij["ljmn"] * Labij["nmca"]
( + 1.0 )  *  Tai["cl"]     * Vabij["jenc"] * Labij["nlea"]
( + 1.0 )  *  Tai["cl"]     * Vabij["lena"] * Labij["njec"]
( - 1.0 )  *  Tai["cl"]     * Vabij["lenc"] * Labij["njea"]
( - 0.5 )  *  Tai["cl"]     * Vabij["efca"] * Labij["ljfe"]
( + 1.0 )  *  Tabij["cdmn"] * Vabij["njda"] * Lai["mc"]
( + 0.5 )  *  Tabij["cdmn"] * Vabij["njcd"] * Lai["ma"]
( + 0.5 )  *  Tabij["cdmn"] * Vabij["mnda"] * Lai["jc"]
( - 0.5 )  *  Tabij["cdmn"] * Vabij["njoa"] * Labij["omdc"]
( - 1.0 )  *  Tabij["cdmn"] * Vabij["njod"] * Labij["omca"]
( - 0.25 ) *  Tabij["cdmn"] * Vabij["mnoa"] * Labij["ojdc"]
( - 0.5 )  *  Tabij["cdmn"] * Vabij["mnod"] * Labij["ojca"]
( - 0.5 )  *  Tabij["cdmn"] * Vabij["jgda"] * Labij["nmgc"]
( - 0.25 ) *  Tabij["cdmn"] * Vabij["jgcd"] * Labij["nmga"]
( - 1.0 )  *  Tabij["cdmn"] * Vabij["ngda"] * Labij["mjgc"]
( - 0.5 )  *  Tabij["cdmn"] * Vabij["ngcd"] * Labij["mjga"]
( - 1.0 )  *  Tai["cl"]     * Tai["en"]     * Vabij["njca"] * Lai["le"]
( - 1.0 )  *  Tai["cl"]     * Tai["en"]     * Vabij["njec"] * Lai["la"]
( - 1.0 )  *  Tai["cl"]     * Tai["en"]     * Vabij["nlea"] * Lai["jc"]
( + 1.0 )  *  Tai["cl"]     * Tai["en"]     * Vabij["njoc"] * Labij["olea"]
( + 0.5 )  *  Tai["cl"]     * Tai["en"]     * Vabij["nloa"] * Labij["ojec"]
( + 1.0 )  *  Tai["cl"]     * Tai["en"]     * Vabij["nloe"] * Labij["ojca"]
( + 0.5 )  *  Tai["cl"]     * Tai["en"]     * Vabij["jgec"] * Labij["nlga"]
( + 1.0 )  *  Tai["cl"]     * Tai["en"]     * Vabij["ngca"] * Labij["ljge"]
( + 1.0 )  *  Tai["cl"]     * Tai["en"]     * Vabij["ngec"] * Labij["ljga"]
( - 0.5 )  *  Tabij["cdmn"] * Tai["gp"]     * Vabij["njga"] * Labij["pmdc"]
( - 1.0 )  *  Tabij["cdmn"] * Tai["gp"]     * Vabij["njgd"] * Labij["pmca"]
( - 0.25 ) *  Tabij["cdmn"] * Tai["gp"]     * Vabij["mnga"] * Labij["pjdc"]
( - 0.5 )  *  Tabij["cdmn"] * Tai["gp"]     * Vabij["mngd"] * Labij["pjca"]
( - 0.5 )  *  Tabij["cdmn"] * Tai["gp"]     * Vabij["pjda"] * Labij["nmgc"]
( - 0.25 ) *  Tabij["cdmn"] * Tai["gp"]     * Vabij["pjcd"] * Labij["nmga"]
( + 0.5 )  *  Tabij["cdmn"] * Tai["gp"]     * Vabij["pjgd"] * Labij["nmca"]
( - 1.0 )  *  Tabij["cdmn"] * Tai["gp"]     * Vabij["pnda"] * Labij["mjgc"]
( - 0.5 )  *  Tabij["cdmn"] * Tai["gp"]     * Vabij["pncd"] * Labij["mjga"]
( + 0.5 )  *  Tabij["cdmn"] * Tai["gp"]     * Vabij["pnga"] * Labij["mjdc"]
( + 1.0 )  *  Tabij["cdmn"] * Tai["gp"]     * Vabij["pngd"] * Labij["mjca"]
( + 0.5 )  *  Tai["cl"]     * Tai["en"]     * Tai["gp"]     * Vabij["pjec"] * Labij["nlga"]
( + 0.5 )  *  Tai["cl"]     * Tai["en"]     * Tai["gp"]     * Vabij["pnca"] * Labij["ljge"]
( - 1.0 )  *  Tai["cl"]     * Tai["en"]     * Tai["gp"]     * Vabij["pngc"] * Labij["ljea"]
