( - 1.0 )  *  Fij["jk"]     * Lai["ka"]
( + 1.0 )  *  Fab["ca"]     * Lai["jc"]
( - 1.0 )  *  Viajb["jcla"] * Lai["lc"]
( - 0.5 )  *  Viajk["jclm"] * Labij["mlca"]
( - 0.5 )  *  Vabic["cdma"] * Labij["mjdc"]
( - 1.0 )  *  Tai["cl"]     * Vijka["ljma"] * Lai["mc"]
( + 1.0 )  *  Tai["cl"]     * Vijka["ljmc"] * Lai["ma"]
( - 1.0 )  *  Tai["cl"]     * Viabc["jeca"] * Lai["le"]
( + 1.0 )  *  Tai["cl"]     * Viabc["leca"] * Lai["je"]
( - 1.0 )  *  Fij["kl"]     * Tai["ek"]     * Labij["ljea"]
( + 1.0 )  *  Fab["cd"]     * Tai["dm"]     * Labij["mjca"]
( - 0.5 )  *  Tai["cl"]     * Vijkl["ljmn"] * Labij["nmca"]
( + 1.0 )  *  Tai["cl"]     * Viajb["jenc"] * Labij["nlea"]
( + 1.0 )  *  Tai["cl"]     * Viajb["lena"] * Labij["njec"]
( - 1.0 )  *  Tai["cl"]     * Viajb["lenc"] * Labij["njea"]
( - 0.5 )  *  Tai["cl"]     * Vabcd["efca"] * Labij["ljfe"]
( + 1.0 )  *  Tabij["cdmn"] * Vijab["njda"] * Lai["mc"]
( + 0.5 )  *  Tabij["cdmn"] * Vijab["njcd"] * Lai["ma"]
( + 0.5 )  *  Tabij["cdmn"] * Vijab["mnda"] * Lai["jc"]
( - 0.5 )  *  Tabij["cdmn"] * Vijka["njoa"] * Labij["omdc"]
( - 1.0 )  *  Tabij["cdmn"] * Vijka["njod"] * Labij["omca"]
( - 0.25 ) *  Tabij["cdmn"] * Vijka["mnoa"] * Labij["ojdc"]
( - 0.5 )  *  Tabij["cdmn"] * Vijka["mnod"] * Labij["ojca"]
( - 0.5 )  *  Tabij["cdmn"] * Viabc["jgda"] * Labij["nmgc"]
( - 0.25 ) *  Tabij["cdmn"] * Viabc["jgcd"] * Labij["nmga"]
( - 1.0 )  *  Tabij["cdmn"] * Viabc["ngda"] * Labij["mjgc"]
( - 0.5 )  *  Tabij["cdmn"] * Viabc["ngcd"] * Labij["mjga"]
( - 1.0 )  *  Tai["cl"]     * Tai["en"]     * Vijab["njca"] * Lai["le"]
( - 1.0 )  *  Tai["cl"]     * Tai["en"]     * Vijab["njec"] * Lai["la"]
( - 1.0 )  *  Tai["cl"]     * Tai["en"]     * Vijab["nlea"] * Lai["jc"]
( + 1.0 )  *  Tai["cl"]     * Tai["en"]     * Vijka["njoc"] * Labij["olea"]
( + 0.5 )  *  Tai["cl"]     * Tai["en"]     * Vijka["nloa"] * Labij["ojec"]
( + 1.0 )  *  Tai["cl"]     * Tai["en"]     * Vijka["nloe"] * Labij["ojca"]
( + 0.5 )  *  Tai["cl"]     * Tai["en"]     * Viabc["jgec"] * Labij["nlga"]
( + 1.0 )  *  Tai["cl"]     * Tai["en"]     * Viabc["ngca"] * Labij["ljge"]
( + 1.0 )  *  Tai["cl"]     * Tai["en"]     * Viabc["ngec"] * Labij["ljga"]
( - 0.5 )  *  Tabij["cdmn"] * Tai["gp"]     * Vijab["njga"] * Labij["pmdc"]
( - 1.0 )  *  Tabij["cdmn"] * Tai["gp"]     * Vijab["njgd"] * Labij["pmca"]
( - 0.25 ) *  Tabij["cdmn"] * Tai["gp"]     * Vijab["mnga"] * Labij["pjdc"]
( - 0.5 )  *  Tabij["cdmn"] * Tai["gp"]     * Vijab["mngd"] * Labij["pjca"]
( - 0.5 )  *  Tabij["cdmn"] * Tai["gp"]     * Vijab["pjda"] * Labij["nmgc"]
( - 0.25 ) *  Tabij["cdmn"] * Tai["gp"]     * Vijab["pjcd"] * Labij["nmga"]
( + 0.5 )  *  Tabij["cdmn"] * Tai["gp"]     * Vijab["pjgd"] * Labij["nmca"]
( - 1.0 )  *  Tabij["cdmn"] * Tai["gp"]     * Vijab["pnda"] * Labij["mjgc"]
( - 0.5 )  *  Tabij["cdmn"] * Tai["gp"]     * Vijab["pncd"] * Labij["mjga"]
( + 0.5 )  *  Tabij["cdmn"] * Tai["gp"]     * Vijab["pnga"] * Labij["mjdc"]
( + 1.0 )  *  Tabij["cdmn"] * Tai["gp"]     * Vijab["pngd"] * Labij["mjca"]
( + 0.5 )  *  Tai["cl"]     * Tai["en"]     * Tai["gp"]     * Vijab["pjec"] * Labij["nlga"]
( + 0.5 )  *  Tai["cl"]     * Tai["en"]     * Tai["gp"]     * Vijab["pnca"] * Labij["ljge"]
( - 1.0 )  *  Tai["cl"]     * Tai["en"]     * Tai["gp"]     * Vijab["pngc"] * Labij["ljea"]
