( - 1.0 + 1.0 * P("klba", "klab") )     *  Vijka["klmb"]          * Lai["ma"]
( + 1.0 - 1.0 * P("klab", "lkab") )     *  Viabc["keab"]          * Lai["le"]
( - 1.0 + 1.0 * P("klab", "lkab") )     *  Fij["km"]              * Labij["mlab"]
( - 1.0 + 1.0 * P("klba", "klab") )     *  Fab["eb"]              * Labij["klea"]
( - 0.5 )     *  Vijkl["klmn"]          * Labij["nmab"]
( + 1.0 - 1.0 * P("klba", "klab") - 1.0 * P("klba", "lkba") + 1.0 * P("klba", "lkab") ) *  Viajb["kenb"] * Labij["nlea"]
( - 0.5 )     *  Vabcd["efab"]          * Labij["klfe"]
( - 1.0 + 1.0 * P("klba", "klab") )     *  Tai["en"]              * Vijab["kleb"]       * Lai["na"]
( + 1.0 - 1.0 * P("klab", "lkab") )     *  Tai["en"]              * Vijab["nkab"]       * Lai["le"]
( - 1.0 + 1.0 * P("klba", "klab") + 1.0 * P("klba", "lkba") - 1.0 * P("klba", "lkab") ) *  Tai["en"]     * Vijab["nkeb"] * Lai["la"]
( + 1.0 )     *  Tai["en"]              * Vijka["kloe"]           * Labij["onab"]
( + 1.0 - 1.0 * P("klba", "klab") - 1.0 * P("klba", "lkba") + 1.0 * P("klba", "lkab") ) *  Tai["en"]     * Vijka["nkob"] * Labij["olea"]
( + 1.0 - 1.0 * P("klab", "lkab") )     *  Tai["en"]              * Vijka["nkoe"]       * Labij["olab"]
( + 1.0 - 1.0 * P("klba", "klab") - 1.0 * P("klba", "lkba") + 1.0 * P("klba", "lkab") ) *  Tai["en"]     * Viabc["kgeb"] * Labij["nlga"]
( + 1.0 )     *  Tai["en"]              * Viabc["ngab"]           * Labij["klge"]
( - 1.0 + 1.0 * P("klba", "klab") )     *  Tai["en"]              * Viabc["ngeb"]       * Labij["klga"]
( + 0.5 - 0.5 * P("klba", "klab") )     *  Tabij["efop"]          * Vijab["klfb"]       * Labij["poea"]
( - 0.25 )    *  Tabij["efop"]          * Vijab["klef"]           * Labij["poab"]
( - 0.5 + 0.5 * P("klab", "lkab") )     *  Tabij["efop"]          * Vijab["pkab"]       * Labij["olfe"]
( - 1.0 + 1.0 * P("klba", "klab") + 1.0 * P("klba", "lkba") - 1.0 * P("klba", "lkab") ) *  Tabij["efop"] * Vijab["pkfb"] * Labij["olea"]
( + 0.5 - 0.5 * P("klab", "lkab") )     *  Tabij["efop"]          * Vijab["pkef"]       * Labij["olab"]
( - 0.25 )    *  Tabij["efop"]          * Vijab["opab"]           * Labij["klfe"]
( - 0.5 + 0.5 * P("klba", "klab") )     *  Tabij["efop"]          * Vijab["opfb"]       * Labij["klea"]
( + 0.5 )     *  Tai["en"]              * Tai["gp"]               * Vijab["klge"]       * Labij["pnab"]
( + 1.0 - 1.0 * P("klba", "klab") - 1.0 * P("klba", "lkba") + 1.0 * P("klba", "lkab") ) *  Tai["en"]     * Tai["gp"]     * Vijab["pkeb"] * Labij["nlga"]
( - 1.0 + 1.0 * P("klab", "lkab") )     *  Tai["en"]              * Tai["gp"]           * Vijab["pkge"]  * Labij["nlab"]
( + 0.5 )     *  Tai["en"]              * Tai["gp"]               * Vijab["pnab"]       * Labij["klge"]
( + 1.0 - 1.0 * P("klba", "klab") )     *  Tai["en"]              * Tai["gp"]           * Vijab["pngb"]  * Labij["klea"]
