( - 1.0 + 1.0 * P("klba", "klab") + 1.0 * P("klba", "lkba") - 1.0 * P("klba", "lkab") ) * Fai["kb"]      * Lai["la"]
( - 1.0 + 1.0 * P("klba", "klab") )     *  Vabij["klmb"]          * Lai["ma"]
( + 1.0 - 1.0 * P("klab", "lkab") )     *  Vabij["keab"]          * Lai["le"]
( - 1.0 + 1.0 * P("klab", "lkab") )     *  Fai["km"]              * Labij["mlab"]
( - 1.0 + 1.0 * P("klba", "klab") )     *  Fab["eb"]              * Labij["klea"]
( - 0.5 )     *  Vabij["klmn"]          * Labij["nmab"]
( + 1.0 - 1.0 * P("klba", "klab") - 1.0 * P("klba", "lkba") + 1.0 * P("klba", "lkab") ) *  Vabij["kenb"] * Labij["nlea"]
( - 0.5 )     *  Vabij["efab"]          * Labij["klfe"]
( - 1.0 + 1.0 * P("klba", "klab") )     *  Tai["en"]              * Vabij["kleb"]       * Lai["na"]
( + 1.0 - 1.0 * P("klab", "lkab") )     *  Tai["en"]              * Vabij["nkab"]       * Lai["le"]
( - 1.0 + 1.0 * P("klba", "klab") + 1.0 * P("klba", "lkba") - 1.0 * P("klba", "lkab") ) *  Tai["en"]     * Vabij["nkeb"] * Lai["la"]
( - 1.0 + 1.0 * P("klab", "lkab") )     *  Fai["ke"]              * Tai["en"]           * Labij["nlab"]
( + 1.0 - 1.0 * P("klba", "klab") )     *  Fai["mb"]              * Tai["fm"]           * Labij["klfa"]
( + 1.0 )     *  Tai["en"]              * Vabij["kloe"]           * Labij["onab"]
( + 1.0 - 1.0 * P("klba", "klab") - 1.0 * P("klba", "lkba") + 1.0 * P("klba", "lkab") ) *  Tai["en"]     * Vabij["nkob"] * Labij["olea"]
( + 1.0 - 1.0 * P("klab", "lkab") )     *  Tai["en"]              * Vabij["nkoe"]       * Labij["olab"]
( + 1.0 - 1.0 * P("klba", "klab") - 1.0 * P("klba", "lkba") + 1.0 * P("klba", "lkab") ) *  Tai["en"]     * Vabij["kgeb"] * Labij["nlga"]
( + 1.0 )     *  Tai["en"]              * Vabij["ngab"]           * Labij["klge"]
( - 1.0 + 1.0 * P("klba", "klab") )     *  Tai["en"]              * Vabij["ngeb"]       * Labij["klga"]
( + 0.5 - 0.5 * P("klba", "klab") )     *  Tabij["efop"]          * Vabij["klfb"]       * Labij["poea"]
( - 0.25 )    *  Tabij["efop"]          * Vabij["klef"]           * Labij["poab"]
( - 0.5 + 0.5 * P("klab", "lkab") )     *  Tabij["efop"]          * Vabij["pkab"]       * Labij["olfe"]
( - 1.0 + 1.0 * P("klba", "klab") + 1.0 * P("klba", "lkba") - 1.0 * P("klba", "lkab") ) *  Tabij["efop"] * Vabij["pkfb"] * Labij["olea"]
( + 0.5 - 0.5 * P("klab", "lkab") )     *  Tabij["efop"]          * Vabij["pkef"]       * Labij["olab"]
( - 0.25 )    *  Tabij["efop"]          * Vabij["opab"]           * Labij["klfe"]
( - 0.5 + 0.5 * P("klba", "klab") )     *  Tabij["efop"]          * Vabij["opfb"]       * Labij["klea"]
( + 0.5 )     *  Tai["en"]              * Tai["gp"]               * Vabij["klge"]       * Labij["pnab"]
( + 1.0 - 1.0 * P("klba", "klab") - 1.0 * P("klba", "lkba") + 1.0 * P("klba", "lkab") ) *  Tai["en"]     * Tai["gp"]     * Vabij["pkeb"] * Labij["nlga"]
( - 1.0 + 1.0 * P("klab", "lkab") )     *  Tai["en"]              * Tai["gp"]           * Vabij["pkge"]  * Labij["nlab"]
( + 0.5 )     *  Tai["en"]              * Tai["gp"]               * Vabij["pnab"]       * Labij["klge"]
( + 1.0 - 1.0 * P("klba", "klab") )     *  Tai["en"]              * Tai["gp"]           * Vabij["pngb"]  * Labij["klea"]
