( - 1.0 ) *  Fij["ki"]     * Rai["bk"]
( + 1.0 ) *  Fab["bc"]     * Rai["ci"]
( - 1.0 ) *  Viajb["kbid"] * Rai["dk"]
( + 0.5 ) *  Vijka["klie"] * Rabij["ebkl"]
( + 0.5 ) *  Viabc["kbde"] * Rabij["deki"]
( - 1.0 ) *  Tai["bk"]     * Vijka["klie"] * Rai["el"]
( + 1.0 ) *  Tai["cl"]     * Vijka["lmic"] * Rai["bm"]
( - 1.0 ) *  Tai["ci"]     * Viabc["lbce"] * Rai["el"]
( + 1.0 ) *  Tai["cl"]     * Viabc["lbce"] * Rai["ei"]
( + 0.5 ) *  Tai["ci"]     * Vijab["lmcf"] * Rabij["fblm"]
( + 0.5 ) *  Tai["bk"]     * Vijab["klef"] * Rabij["efli"]
( + 1.0 ) *  Tai["cl"]     * Vijab["lmcf"] * Rabij["fbmi"]
( + 1.0 ) *  Tabij["cbli"] * Vijab["lmcf"] * Rai["fm"]
( - 0.5 ) *  Tabij["cdmi"] * Vijab["mncd"] * Rai["bn"]
( - 0.5 ) *  Tabij["cblm"] * Vijab["lmcf"] * Rai["fi"]
( - 1.0 ) *  Tai["ci"]     * Tai["bl"]     * Vijab["lmcf"] * Rai["fm"]
( + 1.0 ) *  Tai["ci"]     * Tai["dm"]     * Vijab["mncd"] * Rai["bn"]
( + 1.0 ) *  Tai["bk"]     * Tai["dm"]     * Vijab["kmdf"] * Rai["fi"]
