( - 1.0 ) *  Fij["ki"]     * Rai["bk"]
( + 1.0 ) *  Fab["bc"]     * Rai["ci"]
( - 1.0 ) *  Vabij["kbid"] * Rai["dk"]
( + 0.5 ) *  Vabij["klie"] * Rabij["ebkl"]
( + 0.5 ) *  Vabij["kbde"] * Rabij["deki"]
( - 1.0 ) *  Tai["bk"]     * Vabij["klie"] * Rai["el"]
( + 1.0 ) *  Tai["cl"]     * Vabij["lmic"] * Rai["bm"]
( - 1.0 ) *  Tai["ci"]     * Vabij["lbce"] * Rai["el"]
( + 1.0 ) *  Tai["cl"]     * Vabij["lbce"] * Rai["ei"]
( + 0.5 ) *  Tai["ci"]     * Vabij["lmcf"] * Rabij["fblm"]
( + 0.5 ) *  Tai["bk"]     * Vabij["klef"] * Rabij["efli"]
( + 1.0 ) *  Tai["cl"]     * Vabij["lmcf"] * Rabij["fbmi"]
( + 1.0 ) *  Tabij["cbli"] * Vabij["lmcf"] * Rai["fm"]
( - 0.5 ) *  Tabij["cdmi"] * Vabij["mncd"] * Rai["bn"]
( - 0.5 ) *  Tabij["cblm"] * Vabij["lmcf"] * Rai["fi"]
( - 1.0 ) *  Tai["ci"]     * Tai["bl"]     * Vabij["lmcf"] * Rai["fm"]
( + 1.0 ) *  Tai["ci"]     * Tai["dm"]     * Vabij["mncd"] * Rai["bn"]
( + 1.0 ) *  Tai["bk"]     * Tai["dm"]     * Vabij["kmdf"] * Rai["fi"]
