( - 1.0 + 1.0 * P("dcij", "cdij") )     *  Vabij["mdij"]          * Rai["cm"]
( + 1.0 - 1.0 * P("cdij", "cdji") )     *  Vabij["cdie"]          * Rai["ej"]
( - 1.0 + 1.0 * P("cdij", "cdji") )     *  Fai["mi"]              * Rabij["cdmj"]
( - 1.0 + 1.0 * P("dcij", "cdij") )     *  Fai["de"]              * Rabij["ecij"]
( + 0.5 )     *  Vabij["mnij"]          * Rabij["cdmn"]
( + 1.0 - 1.0 * P("dcij", "cdij") - 1.0 * P("dcij", "dcji") + 1.0 * P("dcij", "cdji") ) *  Vabij["mdif"] * Rabij["fcmj"]
( + 0.5 )     *  Vabij["cdef"]          * Rabij["efij"]
( - 1.0 + 1.0 * P("dcij", "cdij") )     *  Tai["dm"]              * Vabij["mnij"]       * Rai["cn"]
( - 1.0 + 1.0 * P("dcji", "cdji") + 1.0 * P("dcji", "dcij") - 1.0 * P("dcji", "cdij") ) *  Tai["ej"]     * Vabij["ndie"] * Rai["cn"]
( - 1.0 + 1.0 * P("cdij", "dcij") + 1.0 * P("cdij", "cdji") - 1.0 * P("cdij", "dcji") ) *  Tai["cm"]     * Vabij["mdif"] * Rai["fj"]
( + 1.0 - 1.0 * P("cdij", "cdji") )     *  Tai["ei"]              * Vabij["cdef"]       * Rai["fj"]
( - 1.0 + 1.0 * P("cdij", "cdji") )     *  Fai["mf"]              * Tai["fi"]           * Rabij["cdmj"]
( + 1.0 - 1.0 * P("dcij", "cdij") )     *  Fai["mf"]              * Tai["dm"]           * Rabij["fcij"]
( + 0.5 - 0.5 * P("cdji", "cdij") )     *  Tai["ej"]              * Vabij["noie"]       * Rabij["cdno"]
( + 1.0 - 1.0 * P("dcij", "cdij") - 1.0 * P("dcij", "dcji") + 1.0 * P("dcij", "cdji") ) *  Tai["dm"]     * Vabij["mnig"] * Rabij["gcnj"]
( + 1.0 - 1.0 * P("cdij", "cdji") )     *  Tai["en"]              * Vabij["noie"]       * Rabij["cdoj"]
( + 1.0 - 1.0 * P("dcij", "cdij") - 1.0 * P("dcij", "dcji") + 1.0 * P("dcij", "cdji") ) *  Tai["ei"]     * Vabij["ndeg"] * Rabij["gcnj"]
( - 0.5 + 0.5 * P("cdij", "dcij") )     *  Tai["cm"]              * Vabij["mdfg"]       * Rabij["fgij"]
( - 1.0 + 1.0 * P("dcij", "cdij") )     *  Tai["en"]              * Vabij["ndeg"]       * Rabij["gcij"]
( - 1.0 + 1.0 * P("dcij", "cdij") )     *  Fai["mf"]              * Tabij["fdij"]       * Rai["cm"]
( + 1.0 - 1.0 * P("cdij", "cdji") )     *  Fai["mf"]              * Tabij["cdmi"]       * Rai["fj"]
( - 1.0 + 1.0 * P("cdji", "cdij") )     *  Tabij["cdmj"]          * Vabij["mnig"]       * Rai["gn"]
( + 1.0 - 1.0 * P("dcji", "cdji") - 1.0 * P("dcji", "dcij") + 1.0 * P("dcji", "cdij") ) *  Tabij["ednj"] * Vabij["noie"] * Rai["co"]
( + 0.5 - 0.5 * P("cdij", "cdji") )     *  Tabij["cdmn"]          * Vabij["mnig"]       * Rai["gj"]
( + 1.0 - 1.0 * P("cdij", "dcij") )     *  Tabij["ecij"]          * Vabij["ndeg"]       * Rai["gn"]
( - 0.5 + 0.5 * P("dcij", "cdij") )     *  Tabij["efij"]          * Vabij["odef"]       * Rai["co"]
( + 1.0 - 1.0 * P("cdij", "dcij") - 1.0 * P("cdij", "cdji") + 1.0 * P("cdij", "dcji") ) *  Tabij["ecni"] * Vabij["ndeg"] * Rai["gj"]
( + 0.5 - 0.5 * P("dcij", "cdij") )     *  Tabij["edij"]          * Vabij["noeh"]       * Rabij["hcno"]
( + 0.25 )    *  Tabij["efij"]          * Vabij["opef"]           * Rabij["cdop"]
( - 0.5 + 0.5 * P("cdij", "cdji") )     *  Tabij["cdmi"]          * Vabij["mngh"]       * Rabij["ghnj"]
( - 1.0 + 1.0 * P("dcij", "cdij") + 1.0 * P("dcij", "dcji") - 1.0 * P("dcij", "cdji") ) *  Tabij["edni"] * Vabij["noeh"] * Rabij["hcoj"]
( - 0.5 + 0.5 * P("cdij", "cdji") )     *  Tabij["efoi"]          * Vabij["opef"]       * Rabij["cdpj"]
( + 0.25 )    *  Tabij["cdmn"]          * Vabij["mngh"]           * Rabij["ghij"]
( + 0.5 - 0.5 * P("dcij", "cdij") )     *  Tabij["edno"]          * Vabij["noeh"]       * Rabij["hcij"]
( - 1.0 + 1.0 * P("dcji", "cdji") + 1.0 * P("dcji", "dcij") - 1.0 * P("dcji", "cdij") ) *  Tai["ej"]     * Tai["dn"]     * Vabij["noie"] * Rai["co"]
( + 1.0 - 1.0 * P("cdij", "cdji") )     *  Tai["cm"]              * Tai["dn"]           * Vabij["mnig"]  * Rai["gj"]
( - 1.0 + 1.0 * P("dcij", "cdij") )     *  Tai["ei"]              * Tai["fj"]           * Vabij["odef"]  * Rai["co"]
( - 1.0 + 1.0 * P("cdij", "dcij") + 1.0 * P("cdij", "cdji") - 1.0 * P("cdij", "dcji") ) *  Tai["ei"]     * Tai["cn"]     * Vabij["ndeg"] * Rai["gj"]
( + 0.5 )     *  Tai["ei"]              * Tai["fj"]               * Vabij["opef"]       * Rabij["cdop"]
( + 1.0 - 1.0 * P("dcij", "cdij") - 1.0 * P("dcij", "dcji") + 1.0 * P("dcij", "cdji") ) *  Tai["ei"]     * Tai["dn"]     * Vabij["noeh"] * Rabij["hcoj"]
( + 1.0 - 1.0 * P("cdij", "cdji") )     *  Tai["ei"]              * Tai["fo"]           * Vabij["opef"]  * Rabij["cdpj"]
( + 0.5 )     *  Tai["cm"]              * Tai["dn"]               * Vabij["mngh"]       * Rabij["ghij"]
( - 1.0 + 1.0 * P("dcij", "cdij") )     *  Tai["dm"]              * Tai["fo"]           * Vabij["mofh"]  * Rabij["hcij"]
( - 1.0 + 1.0 * P("cdji", "cdij") )     *  Tabij["cdmj"]          * Tai["fi"]           * Vabij["mofh"]  * Rai["ho"]
( - 1.0 + 1.0 * P("dcji", "cdji") + 1.0 * P("dcji", "dcij") - 1.0 * P("dcji", "cdij") ) *  Tabij["ednj"] * Tai["gi"]     * Vabij["npeg"] * Rai["cp"]
( + 0.5 - 0.5 * P("cdij", "cdji") )     *  Tabij["cdmn"]          * Tai["gi"]           * Vabij["mngh"]  * Rai["hj"]
( + 1.0 - 1.0 * P("cdij", "dcij") )     *  Tabij["ecij"]          * Tai["dn"]           * Vabij["noeh"]  * Rai["ho"]
( - 0.5 + 0.5 * P("dcij", "cdij") )     *  Tabij["efij"]          * Tai["do"]           * Vabij["opef"]  * Rai["cp"]
( + 1.0 - 1.0 * P("dcij", "cdij") )     *  Tabij["edij"]          * Tai["fo"]           * Vabij["opef"]  * Rai["cp"]
( - 1.0 + 1.0 * P("cdij", "dcij") + 1.0 * P("cdij", "cdji") - 1.0 * P("cdij", "dcji") ) *  Tabij["ecni"] * Tai["do"]     * Vabij["noeh"] * Rai["hj"]
( - 1.0 + 1.0 * P("cdij", "cdji") )     *  Tabij["cdmi"]          * Tai["fo"]           * Vabij["mofh"]  * Rai["hj"]
( - 1.0 + 1.0 * P("dcij", "cdij") )     *  Tai["ei"]              * Tai["fj"]           * Tai["do"]      * Vabij["opef"] * Rai["cp"]
( + 1.0 - 1.0 * P("cdij", "cdji") )     *  Tai["ei"]              * Tai["cn"]           * Tai["do"]      * Vabij["noeh"] * Rai["hj"]
