( - 1.0 )  *  Fij["jk"]     * Lai["ka"]
( + 1.0 )  *  Fab["ca"]     * Lai["jc"]
( - 1.0 )  *  Viajb["jcla"] * Lai["lc"]
( - 0.5 )  *  Viajk["jclm"] * Labij["mlca"]
( - 0.5 )  *  Vabic["cdma"] * Labij["mjdc"]
( + 1.0 )  *  Tabij["cdmn"] * Vijab["njda"] * Lai["mc"]
( + 0.5 )  *  Tabij["cdmn"] * Vijab["njcd"] * Lai["ma"]
( + 0.5 )  *  Tabij["cdmn"] * Vijab["mnda"] * Lai["jc"]
( - 0.5 )  *  Tabij["cdmn"] * Vijka["njoa"] * Labij["omdc"]
( - 1.0 )  *  Tabij["cdmn"] * Vijka["njod"] * Labij["omca"]
( - 0.25 ) *  Tabij["cdmn"] * Vijka["mnoa"] * Labij["ojdc"]
( - 0.5 )  *  Tabij["cdmn"] * Vijka["mnod"] * Labij["ojca"]
( - 0.5 )  *  Tabij["cdmn"] * Viabc["jgda"] * Labij["nmgc"]
( - 0.25 ) *  Tabij["cdmn"] * Viabc["jgcd"] * Labij["nmga"]
( - 1.0 )  *  Tabij["cdmn"] * Viabc["ngda"] * Labij["mjgc"]
( - 0.5 )  *  Tabij["cdmn"] * Viabc["ngcd"] * Labij["mjga"]
