( - 1.0 )  *  Fij[jk]       * Lai["ka"]
( + 1.0 )  *  Fab[ca]       * Lai["jc"]
( - 1.0 )  *  Vabij["jcla"] * Lai["lc"]
( - 0.5 )  *  Vabij["jclm"] * Labij["mlca"]
( - 0.5 )  *  Vabij["cdma"] * Labij["mjdc"]
( + 1.0 )  *  Tabij["cdmn"] * Vabij["njda"] * Lai["mc"]
( + 0.5 )  *  Tabij["cdmn"] * Vabij["njcd"] * Lai["ma"]
( + 0.5 )  *  Tabij["cdmn"] * Vabij["mnda"] * Lai["jc"]
( - 0.5 )  *  Tabij["cdmn"] * Vabij["njoa"] * Labij["omdc"]
( - 1.0 )  *  Tabij["cdmn"] * Vabij["njod"] * Labij["omca"]
( - 0.25 ) *  Tabij["cdmn"] * Vabij["mnoa"] * Labij["ojdc"]
( - 0.5 )  *  Tabij["cdmn"] * Vabij["mnod"] * Labij["ojca"]
( - 0.5 )  *  Tabij["cdmn"] * Vabij["jgda"] * Labij["nmgc"]
( - 0.25 ) *  Tabij["cdmn"] * Vabij["jgcd"] * Labij["nmga"]
( - 1.0 )  *  Tabij["cdmn"] * Vabij["ngda"] * Labij["mjgc"]
( - 0.5 )  *  Tabij["cdmn"] * Vabij["ngcd"] * Labij["mjga"]
