( - 1.0 + 1.0 * P("klba", "klab") )     *  Vabij["klmb"]          * Lai["ma"]
( + 1.0 - 1.0 * P("klab", "lkab") )     *  Vabij["keab"]          * Lai["le"]
( - 1.0 + 1.0 * P("klab", "lkab") )     *  Fij["km"]              * Labij["mlab"]
( - 1.0 + 1.0 * P("klba", "klab") )     *  Fab["eb"]              * Labij["klea"]
( - 0.5 )     *  Vabij["klmn"]          * Labij["nmab"]
( + 1.0 - 1.0 * P("klba", "klab") - 1.0 * P("klba", "lkba") + 1.0 * P("klba", "lkab") ) *  Vabij["kenb"] * Labij["nlea"]
( - 0.5 )     *  Vabij["efab"]          * Labij["klfe"]
( + 0.5 - 0.5 * P("klba", "klab") )     *  Tabij["efop"]          * Vabij["klfb"]       * Labij["poea"]
( - 0.25 )    *  Tabij["efop"]          * Vabij["klef"]           * Labij["poab"]
( - 0.5 + 0.5 * P("klab", "lkab") )     *  Tabij["efop"]          * Vabij["pkab"]       * Labij["olfe"]
( - 1.0 + 1.0 * P("klba", "klab") + 1.0 * P("klba", "lkba") - 1.0 * P("klba", "lkab") ) *  Tabij["efop"] * Vabij["pkfb"] * Labij["olea"]
( + 0.5 - 0.5 * P("klab", "lkab") )     *  Tabij["efop"]          * Vabij["pkef"]       * Labij["olab"]
( - 0.25 )    *  Tabij["efop"]          * Vabij["opab"]           * Labij["klfe"]
( - 0.5 + 0.5 * P("klba", "klab") )     *  Tabij["efop"]          * Vabij["opfb"]       * Labij["klea"]
