( - 1.0 + 1.0 * P("dcij", "cdij") )     *  Viajk["mdij"]          * Rai["cm"]
( + 1.0 - 1.0 * P("cdij", "cdji") )     *  Vabic["cdie"]          * Rai["ej"]
( - 1.0 + 1.0 * P("cdij", "cdji") )     *  Fij["mi"]              * Rabij["cdmj"]
( - 1.0 + 1.0 * P("dcij", "cdij") )     *  Fab["de"]              * Rabij["ecij"]
( + 0.5 )     *  Vijkl["mnij"]          * Rabij["cdmn"]
( + 1.0 - 1.0 * P("dcij", "cdij") - 1.0 * P("dcij", "dcji") + 1.0 * P("dcij", "cdji") ) *  Viajb["mdif"] * Rabij["fcmj"]
( + 0.5 )     *  Vabcd["cdef"]          * Rabij["efij"]
( - 1.0 + 1.0 * P("cdji", "cdij") )     *  Tabij["cdmj"]          * Vijka["mnig"]       * Rai["gn"]
( + 1.0 - 1.0 * P("dcji", "cdji") - 1.0 * P("dcji", "dcij") + 1.0 * P("dcji", "cdij") ) *  Tabij["ednj"] * Vijka["noie"] * Rai["co"]
( + 0.5 - 0.5 * P("cdij", "cdji") )     *  Tabij["cdmn"]          * Vijka["mnig"]       * Rai["gj"]
( + 1.0 - 1.0 * P("cdij", "dcij") )     *  Tabij["ecij"]          * Viabc["ndeg"]       * Rai["gn"]
( - 0.5 + 0.5 * P("dcij", "cdij") )     *  Tabij["efij"]          * Viabc["odef"]       * Rai["co"]
( + 1.0 - 1.0 * P("cdij", "dcij") - 1.0 * P("cdij", "cdji") + 1.0 * P("cdij", "dcji") ) *  Tabij["ecni"] * Viabc["ndeg"] * Rai["gj"]
( + 0.5 - 0.5 * P("dcij", "cdij") )     *  Tabij["edij"]          * Vijab["noeh"]       * Rabij["hcno"]
( + 0.25 )    *  Tabij["efij"]          * Vijab["opef"]           * Rabij["cdop"]
( - 0.5 + 0.5 * P("cdij", "cdji") )     *  Tabij["cdmi"]          * Vijab["mngh"]       * Rabij["ghnj"]
( - 1.0 + 1.0 * P("dcij", "cdij") + 1.0 * P("dcij", "dcji") - 1.0 * P("dcij", "cdji") ) *  Tabij["edni"] * Vijab["noeh"] * Rabij["hcoj"]
( - 0.5 + 0.5 * P("cdij", "cdji") )     *  Tabij["efoi"]          * Vijab["opef"]       * Rabij["cdpj"]
( + 0.25 )    *  Tabij["cdmn"]          * Vijab["mngh"]           * Rabij["ghij"]
( + 0.5 - 0.5 * P("dcij", "cdij") )     *  Tabij["edno"]          * Vijab["noeh"]       * Rabij["hcij"]
